#Testcase Options
SampleDownload:
  dl: true
  force: false

#Compile Options
WithDebugMacro: true
WarningOptions: true
CppVersion: c++17
Optimize: true

#Run Options
Run:
  run: true
  samples: true

#Etc
CopyToClipBoard: true
HeaderExpand: true
